package optimusinventory.api.models;

public enum Privilege {
    CREATE_ITEMS,
    READ_ITEMS,
    UPDATE_ITEMS,
    DELETE_ITEMS,
    CREATE_SALES,
    READ_SALES,
    UPDATE_SALES,
    DELETE_SALES,
    CREATE_DEBTORS,
    READ_DEBTORS,
    UPDATE_DEBTORS,
    DELETE_DEBTORS,
    CREATE_ACCOUNTS,
    READ_ACCOUNTS,
    UPDATE_ACCOUNTS,
    DELETE_ACCOUNTS,
    CREATE_SUMMARY,
    READ_SUMMARY,
    UPDATE_SUMMARY,
    DELETE_SUMMARY,
    LOGS
}
